//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosovPractice17
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMember
    {
        public int id { get; set; }
        public string Fio { get; set; }
        public string Team { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<int> GoalCount { get; set; }
        public Nullable<int> PassCount { get; set; }
        public Nullable<int> PenaltyTime { get; set; }
        public Nullable<int> Matches { get; set; }
    }
}
